#!/usr/bin/env python3
"""Fetches OpenMoji artwork for every emoji used in content/vocabulary.json.

Downloads 618x618 color PNGs from the OpenMoji repository into
assets/openmoji/<CODEPOINTS>.png (canonical name: FE0F variation selectors
stripped, uppercase hex, dash-joined) and regenerates
lib/generated/openmoji_assets.dart with the set of names that succeeded.
Emojis that OpenMoji doesn't cover simply stay rendered as system emoji.

OpenMoji (https://openmoji.org) is licensed CC BY-SA 4.0.

Usage: python3 tool/fetch_openmoji.py  (from the repo root)
"""

import json
import pathlib
import sys
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets" / "openmoji"
GENERATED = ROOT / "lib" / "generated" / "openmoji_assets.dart"
BASE_URL = "https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/618x618"


def canonical_name(emoji: str) -> str:
    """FE0F-stripped, uppercase, 4+-digit, dash-joined codepoints (mirrors
    the Dart side in lib/logic/open_moji.dart)."""
    points = [f"{ord(ch):04X}" for ch in emoji if ord(ch) != 0xFE0F]
    return "-".join(points)


def candidates(emoji: str) -> list[str]:
    """Filenames OpenMoji might use: with and without FE0F."""
    with_fe0f = "-".join(f"{ord(ch):04X}" for ch in emoji)
    without = canonical_name(emoji)
    return list(dict.fromkeys([without, with_fe0f]))


def fetch(name: str) -> bytes | None:
    try:
        with urllib.request.urlopen(f"{BASE_URL}/{name}.png", timeout=30) as r:
            return r.read()
    except urllib.error.HTTPError:
        return None


def main() -> int:
    data = json.loads((ROOT / "content" / "vocabulary.json").read_text())
    emojis = {c["emoji"] for c in data["categories"]}
    emojis |= {w["emoji"] for w in data["words"] if w.get("emoji")}

    ASSETS.mkdir(parents=True, exist_ok=True)
    available: set[str] = set()
    misses: list[str] = []

    for emoji in sorted(emojis):
        canon = canonical_name(emoji)
        target = ASSETS / f"{canon}.png"
        if target.exists():
            available.add(canon)
            continue
        blob = None
        for candidate in candidates(emoji):
            blob = fetch(candidate)
            if blob:
                break
        if blob:
            target.write_bytes(blob)
            available.add(canon)
        else:
            misses.append(f"{emoji} ({canon})")

    GENERATED.parent.mkdir(parents=True, exist_ok=True)
    names = ",\n".join(f"  '{name}'" for name in sorted(available))
    GENERATED.write_text(
        "// GENERATED by tool/fetch_openmoji.py — do not edit by hand.\n"
        "// OpenMoji artwork (https://openmoji.org), license CC BY-SA 4.0.\n\n"
        "/// Canonical codepoint names with a bundled OpenMoji PNG in\n"
        "/// assets/openmoji/.\n"
        "const openMojiAvailable = <String>{\n" + names + ",\n};\n"
    )

    print(f"downloaded/present: {len(available)}, missing from OpenMoji: {len(misses)}")
    for miss in misses:
        print(f"  miss: {miss}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
